### ISSUE TITLE
Proposal: rewrite all ABI with custom prefix

### ISSUE THREAD

**Issue by BusyJay** [tikv/grpc-rs#130]
There are both `grpc_xxx` and `grpcwrap_xxx` styles ABI in grpc_sys/src/lib.rs. We only add `grpcwrap` prefix to the ABI written by ourselves. It's clean and simple.

However, upstream sometimes can change the signature of a public ABI without changing its name. Unfortunately, because the name is the same, so the mismatch can't be detected at link time. So it can lead to unexpected behavior. #129 is an example. Upstream changes the signature and usage of alarm, but the crate can still be compiled and linked successfully.

So I propose to rewrite all ABIs in used by adding a `grpcwrap_` prefix. That way we can ensure signature won't be changed unexpectedly. And upstream changes can also be detected by C/C++ compilers at compile time.

**Comment by ishitatsuyuki** [comment]
Is there a reason we're not using bindgen?

**Comment by BusyJay** [comment]
1. Won't have noisy code;
2. Don't have to write headers to get the bindings;
3. Can customize ABI to be more friendly like removing the annoying `reserved` pointers;
4. Not too much bindings to be handled.

**Comment by siddontang** [comment]
@ishitatsuyuki 

The first ABI version is ported from gRPC C# directly, it is so simple that we don't consider bindgen or others.

**Comment by BusyJay** [comment]
Just found a library can do the correctness check for us: https://github.com/alexcrichton/ctest.

**Comment by BusyJay** [comment]
Now bindings are generated by bindgen, the issue is not valid anymore.
