### ISSUE TITLE
needs support for getting peer identity

### ISSUE THREAD

**Issue by ian-p-cooke** [tikv/grpc-rs#193]
I need to get the client identity from the client certificate used to authenticate on the server side (specifically the first rfc822Name/email in the cert's SAN).  If I understand correctly this is accessed from the call's auth context.  I don't see the necessary functions in `RequestContext`  or the grpc-sys crate (`grpc_auth_context_peer_identity`).

Do you have interest in adding support for that?  I can do it myself but I won't have much time over the next few weeks.  I want to see how a grpc implementation compares to [my cap'n proto RPC example](https://github.com/ian-p-cooke/capntls/blob/4dac50cdc4653b2096f72c253dff4f16328b4678/src/server.rs).

**Comment by ian-p-cooke** [comment]
so I started working on this but I'm stuck.  is there anyone who can assist me with this problem?

re: https://github.com/ian-p-cooke/grpc-rs/tree/ipc_secure_test

is there any way passing a non-null *mut variable to C would result in a NULL value on the C side?

I've added a few extern "C" functions to grpc-sys to access the auth_context and a call to `grpc_auth_context_peer_is_authenticated` works fine but a call to `grpc_auth_context_peer_identity` appears to end up with a NULL pointer on the C side.  Here's what I used to run the server: 

    GRPC_TRACE=all GRPC_VERBOSITY=DEBUG cargo run --example greeter_server 2>&1 | egrep '(grpc_auth|self.ctx|isten)'

and the client:

    cargo run --example greeter_client

and I see 

    I0608 07:10:12.489980426  159097 security_context.c:201]     grpc_auth_context_peer_is_authenticated(ctx=0x7f8fa461f100)
    self.ctx: 0x7f8fa461f100
    I0608 07:10:12.490196213  159097 security_context.c:251]     grpc_auth_context_peer_identity(ctx=(nil))

how is that second call 'nil' when my pointer is definitely non-null (asserted as such and printed value) and the previous call has the right value?

this is only the second time I'm working with FFI and I feel I must be missing something but I can't see what it is.

The extern "C" functions are [here](https://github.com/ian-p-cooke/grpc-rs/blob/ipc_secure_test/grpc-sys/src/lib.rs#L414), the wrappers [here](https://github.com/ian-p-cooke/grpc-rs/blob/ipc_secure_test/src/call/server.rs#L104) and the calls are [here](https://github.com/ian-p-cooke/grpc-rs/blob/ipc_secure_test/examples/hello_world/server.rs#L54)

**Comment by BusyJay** [comment]
The ABI `grpc_auth_context_peer_identity` you define is wrong, which messes up the stack.

**Comment by ian-p-cooke** [comment]
Ah!  thanks for the hint.  I found [the error](https://github.com/ian-p-cooke/grpc-rs/commit/965a1f105d69799579441f9d49296d6b019c25a1) and now it works. 

Unfortunately for me, grpc core is filtering out my SAN.  It only considers DNS names as valid and mine is an rfc822 name (email).  I'll probably have to re-parse the cert myself with openssl and get at my SAN that way.  I suppose I could put email address in CN (as `CN=blah/emailAddress=blah@blah.com`) but that's been deprecated in favor of email SANs.

in any case, I'll keep playing with my use case and submit a PR when I have the new functions all working.

**Comment by ian-p-cooke** [comment]
I'm still working on this but have been side-tracked by [a grpc issue](https://github.com/grpc/grpc/issues/15700).  I'll give that another day to get some sort of attention and then just assume grpc isn't going to accept a change to support my use case.
