### ISSUE TITLE
Add support for async/await syntax

### ISSUE THREAD

**Issue by thedrow** [tikv/grpc-rs#237]
Futures 0.3 is still in alpha and the async/await syntax hasn't stabilized yet but I think we should prepare for the move in a separate branch if possible.
This is issue is for the discussion of work items to be done before we can merge this.

- [x] async/await syntax is stabilized
- [ ] upgrade to futures 0.3

Anything else?

**Comment by siddontang** [comment]
yes @thedrow 

We have been planning to move to Future 0.3, not only in grpc-rs, but also in TiKV. 

Feel feel to send us an alpha branch which uses Future 0.3

**Comment by rbtcollins** [comment]
So this works today using the futures-preview compat layer.

In Cargo.toml:
```
futures = "0.1.28"
futures03 = { package="futures-preview", version = "0.3.0-alpha.17", features = ["compat"] }
grpcio = "0.4.4"
```

`build.rs` as normal.

Then in your code import the compat trait:
```
use futures03::compat::Future01CompatExt;
```
and use it
...
```
async fn foo() -> Result<()> {
...
let thing = client.some_call_async(&request)?.compat().await;
...
```

There's a blog post - https://rust-lang-nursery.github.io/futures-rs/blog/2019/04/18/compatibility-layer.html

**Comment by nrc** [comment]
async/await is stable on nightly, and will be properly stable in just over 6 weeks, so I don't think there is anything blocking using async/await and futures 0.3

**Comment by lerencao** [comment]
Any updates on this?

**Comment by nrc** [comment]
async/await is stable tomorrow, otherwise there is no update

**Comment by gliderkite** [comment]
Any update on this?

**Comment by BusyJay** [comment]
Sorry to let you wait so long. The PR is finally made as #447. You should be able to use async/await after it's landed (and released).

I rewrote the benchmarks and tests using async/await, it was so natural and smooth that I couldn't wait to land it immediately!
