### ISSUE TITLE
Pre-generate bindings for common targets

### ISSUE THREAD

**Issue by BusyJay** [tikv/grpc-rs#353]
Building bindings at compile time introduces extra dependencies. And clang is hard to install and configure on some platform like centos 7. It will be very convenient that we can pre-generate bindings for common targets like x86_64-unknown-linux-gnu. For others, we can fallback to rust-bindgen at compile time.

**Comment by BusyJay** [comment]
Why close this? Is it fixed?

**Comment by hunterlxt** [comment]
Is there any problem that has not been solved?

**Comment by BusyJay** [comment]
To close the issue, you either provide information why it doesn't have to be fixed, or link to the PR or issues that fixes the issue. And close this when the linked one is merged or closed.

**Comment by hunterlxt** [comment]
https://github.com/tikv/grpc-rs/pull/356
https://github.com/tikv/grpc-rs/pull/430
These two PR resolve the issue. Closed.
