### ISSUE TITLE
Add stability test for grpc-rs

### ISSUE THREAD

**Issue by hunterlxt** [tikv/grpc-rs#385]
**Is your feature request related to a problem? Please describe.**
grpc-rs does not have a stability-related test suite, and in some extreme cases there may be some unexpected cases.

**Describe the solution you'd like**
One solution is to modify the benchmark framework to add more control over the behavior of QPSworker. But the framework itself is implemented according to the interface provided by grpc, so the benmark and stability tests may conflict if they share one QPSworker code. (For example, when I want to simulate disconnection on the network)

Another option is to provide a separate workspace to specifically perform such tests while keeping the benchmarks for performance testing.

PS: this [repo](https://github.com/hunterlxt/grpc-rs/tree/lxt/benchmark-stable) is used to verify the first solution.

**Comment by hunterlxt** [comment]
@BusyJay @nrc  PTAL

**Comment by nrc** [comment]
What exactly do you mean by stability testing?

**Comment by hunterlxt** [comment]
The latest solution is to add some specific services to the existing benchmark worker to achieve the goal we want. Ref the [PR](https://github.com/pingcap/grpc-rs/pull/388)

**Comment by hunterlxt** [comment]
This issue is staled for a long time. Closing it.
