### ISSUE TITLE
Bump 0.5.0 GA

### ISSUE THREAD

**Issue by BusyJay** [tikv/grpc-rs#398]
There have been a lot of alpha releases. And I don't see any problem from tests and benches. Maybe it's time to bump a GA release. But before doing so, I still need to make sure what's left undone.

The only one PR that can still change the interfaces and need to be merged into 0.5.0 is #382.

And #375 brings a new version of gRPC C core. I think it's better that a new GA release catches up with updated C core.

/cc @overvenus @hunterlxt @nrc Do you have any other PRs that needs to be included?

**Comment by eranrund** [comment]
How's 0.5.0 looking? :)

**Comment by BusyJay** [comment]
Will publish it when #322 is merged, which seems a popular feature.

**Comment by nrc** [comment]
> Do you have any other PRs that needs to be included?

I don't.
