### ISSUE TITLE
Why are documents of channel_args and build_args hidden?

### ISSUE THREAD

**Issue by tony612** [tikv/grpc-rs#399]
**Is your feature request related to a problem? Please describe.**

I found documents of `ServerBuilder::channel_args` and `ChannelBuilder::build_args` are hidden. And comments of `build_args` says `users should use the encapsulated API instead.`, but I can't find the "encapsulated API". So how to set options on server side?

For example, gRPC C++'s [ServerBuilder](https://grpc.github.io/grpc/cpp/classgrpc__impl_1_1_server_builder.html) has several functions `Set*` to set the options, but I didn't find how to do this except using `ServerBuilder::channel_args`.

**Describe the solution you'd like**

I think we'd better make docs of these two functions public or/and we can add functions in `ServerBuilder` to set the options.

**Comment by BusyJay** [comment]
You are right, they should be public APIs. Can you help us to make them public (and probably with better comments)?

**Comment by tony612** [comment]
OK. I can help with this.
