### ISSUE TITLE
Update license

### ISSUE THREAD

**Issue by BusyJay** [tikv/grpc-rs#402]
Now that grpc-rs has been moved to tikv organization, we need to update the license too.

I think we can follow the same changes in tikv/tikv#4438.

Any ideas? /cc @siddontang @Hoverbear @nrc

**Comment by nrc** [comment]
We would keep the Apache 2 license, right? Then I think that changing the license headers and the copyright holder is legally OK and we just need to make a big PR to do it. I suppose we should get somebody who represents PingCAP to OK the transfer of copyright. I would use the wording:

```
// Copyright 201X grpc-rs Project Authors. Licensed under Apache-2.0.
```

**Comment by BusyJay** [comment]
I suggest to keep it as `TiKV authors`. It looks like a convention to me that projects under the same organization using the same license holder, such grpc and kubernates.

**Comment by Hoverbear** [comment]
@BusyJay I'm in favor, we need to be careful with the grpc headers though so we don't mangle them.

I can work on this if you'd like. :)

**Comment by BusyJay** [comment]
Sure, thanks!
