### ISSUE TITLE
error handling

### ISSUE THREAD

**Issue by kanekv** [tikv/grpc-rs#408]
What is a good paradigm for returning errors with some context info? `.fail` method doesn't let attach any information. For example golang has ability to attach description to the status code: https://github.com/grpc/grpc-go/blob/master/Documentation/rpc-errors.md

**Comment by BusyJay** [comment]
`.fail` accepts a `RpcStatus`, which can be constructed via `RpcStatus::new(code, Some(description))`.

**Comment by kanekv** [comment]
Great, thanks! And how to get it on the client side?

**Comment by BusyJay** [comment]
I don't think client can send a status code to the server as the protocol defines status code is sent by server. The client can cancel the RPC though.

**Comment by kanekv** [comment]
@BusyJay What I mean is how you read the status code and description string on the client?

**Comment by BusyJay** [comment]
If the status is not OK, it will be treated as error, so you read it by checking `grpcio::Error`.

**Comment by kanekv** [comment]
In this case variant would be `RpcFailure(RpcStatus)`?

**Comment by BusyJay** [comment]
Yes.

**Comment by kanekv** [comment]
Thanks!
