### ISSUE TITLE
Unreasonably large server memory usage

### ISSUE THREAD

**Issue by TheSven73** [tikv/grpc-rs#412]
**Describe the bug**
When doing a simple concurrent client/server ping-pong with max. 10_000 concurrent requests, the memory footprint of the server increases to > 1 gigabyte. Is this unreasonably large?

Note that the client never goes above 200-300 megabytes.

**To Reproduce**
https://github.com/TheSven73/grpc-mem-demo

**Expected behavior**
server process memory should stay bound, just like the client?

**System information**
Ubuntu 18.04 Intel Core i7 laptop.

**Comment by hicqu** [comment]
By default grpc uses BDP algorithm to determine `stream_initial_window_size`. So it will be `4M` for every call. In your demo you create 1M calls, and so the memory usage on server side should be `4G`.

**Comment by hicqu** [comment]
Please consider to set resource quota like this:
```rust
        let mem_quota = ResourceQuota::new(Some("ServerMemQuota"))
            .resize_memory(1024 * 1024 * 1024); // 1G
       let channel_args = ChannelBuilder::new(Arc::clone(&env))
            .set_resource_quota(mem_quota)
            .build_args();
```

**Comment by TheSven73** [comment]
Will do, thank you :)
