### ISSUE TITLE
What's the right way to just run the server forever?

### ISSUE THREAD

**Issue by nicholasbishop** [tikv/grpc-rs#421]
Both of the server examples have code like this:

```rust
server.start();
let (tx, rx) = oneshot::channel();
thread::spawn(move || {
    info!("Press ENTER to exit...");
    let _ = io::stdin().read(&mut [0]).unwrap();
    tx.send(())
});
let _ = rx.wait();
let _ = server.shutdown().wait();
```
Instead of waiting for keyboard input, I would like to just run a server that runs forever. What's the right way to do that?

**Comment by BusyJay** [comment]
How about "futures::future::empty().wait()"?

**Comment by nicholasbishop** [comment]
Works for me, thank you :)

Note that it seemed to want a type annotation, so I ended up using this:

```rust
futures::future::empty::<(), ()>().wait()
```
