### ISSUE TITLE
Support the "Richer error model"

### ISSUE THREAD

**Issue by kennytm** [tikv/grpc-rs#443]
**Is your feature request related to a problem? Please describe.**

According to https://grpc.io/docs/guides/error/#richer-error-model, gRPC supports [embedding `Any` message into the error reply](https://cloud.google.com/apis/design/errors#error_model). 

```proto
message Status {
  int32 code = 1;
  string message = 2;

  // Additional error information that the client code can use to handle
  // the error, such as retry delay or a help link.
  repeated google.protobuf.Any details = 3;
}
```

However, `grpcio` only supports an error message string.

https://github.com/tikv/grpc-rs/blob/d4ba053805dc984d96f075d788d03503e504a1c8/src/call/mod.rs#L154-L162

So if we really want to return structured error information, we need to use some bad code patterns like returning *success* and [include the error info in the *success* response](https://github.com/pingcap/kvproto/blob/2cf9a243b8d589f345de1dbaa9eeffec6afbdc06/proto/kvrpcpb.proto#L128-L133). 

```proto
message GetResponse {
    errorpb.Error region_error = 1;   // <-- wtf?
    KeyError error = 2;               // <-- ಠ_ಠ
    bytes value = 3;
    bool not_found = 4;
}
```

Note that 

> This richer error model is already supported in the C++, Go, Java, Python, and Ruby libraries, and at least the grpc-web and Node.js libraries have open issues requesting it. 

and also [`tower-grpc` exposes the array as opaque bytes](https://docs.rs/tower-grpc/0.1.1/tower_grpc/struct.Status.html#method.details).

**Describe the solution you'd like**

Support the "Richer error model". Add a new `additional_details: Vec<u8>` field with documentation how to encode/decode into protobuf-enabled types.

**Describe alternatives you've considered**

**Additional context**

**Comment by BusyJay** [comment]
Related #284.

The proposal looks good. Do you want to bring it into grpc-rs?

**Comment by BusyJay** [comment]
This will become a breaking change. If you want to land it on 0.5.x, we better use a different name than `details`. We can change the name to follow the convention in 0.6.x.

**Comment by kennytm** [comment]
@BusyJay 

> Do you want to bring it into grpc-rs?

As long as TiKV is still using this package, yes.

> We can change the name to follow the convention in 0.6.x.

Renaming `details: Option<String>` to something else and adding a new `details: Vec<u8>` feels causing too much change for upstream even given a major version bump, and potentially cause hard-to-fix breakage by reusing the name. I'm fine with calling the new field something else.

**Comment by BusyJay** [comment]
Depends on #460.
