### ISSUE TITLE
How to assert that server is running

### ISSUE THREAD

**Issue by bausano** [tikv/grpc-rs#444]
In the project's README, there's a ticked checkbox for "Health check". However, I cannot find any further information about what the health check does. Is there a way for me to assert that the server is open to connections via just the [server handle](https://docs.rs/grpcio/0.5.0/grpcio/struct.Server.html)?

**Comment by BusyJay** [comment]
Health check is a custom service that should be implemented by user. You can refer the design docs here: https://github.com/grpc/grpc/blob/master/doc/health-checking.md.  grpc-rs just exposes the trait definition via protos.

**Comment by bausano** [comment]
Would you recommend any pattern I could use to assert whether the server is running from within the same process? Let's say I start the server, which spawns a new thread pool, and then in my main method I want to start a supervision loop. The loop would bind a new server to the same port if the old one server stops. Maybe I am going completely wrong about this?

**Comment by BusyJay** [comment]
If you want to recover from panic automatically, you should use some tools like supervisor or systemd.

**Comment by bausano** [comment]
This leads to my original, albeit poorly formulated, question. I have a supervisor running in the same process. However I am not sure how to assert when the server is dead without constructing a client for `localhost` or checking that the ports I bound the server on are indeed busy. Simplified, I run something like this on my main thread:

```
loop {
  let server_status = ...;
  if server_status.down() {
    let _server = start_grpc_server();
  }
}
```

I am unsure how to get the status.

**Comment by BusyJay** [comment]
In that case, you can watch the lifetime of server struct. For example, keep a oneshot::Sender with server, once they are dropped, corresponding oneshot::Receiver will be resolved to error.
