### ISSUE TITLE
Which crate to use for programmatic generation with recent versions of grpcio?

### ISSUE THREAD

**Issue by Maher4Ever** [tikv/grpc-rs#462]
Hello there,

According to the README file one should use the [`protoc-grpcio`](https://crates.io/crates/protoc-grpcio) crate for programmatic generation. However, the generated rust code for the gRPC services from this crate still uses futures v0.1; it still emits code that contains:

```rust
::futures::Future<Item = (), Error = ()>
```

`grpcio` recently [switched to futures 0.3](https://github.com/tikv/grpc-rs/pull/447) so I was surprised that the examples and tests still worked. After some digging, I stumbled upon the [`protobuf-build`](https://github.com/tikv/protobuf-build) crate which the examples use instead of `protoc-grpcio`.

My question is: Is the README file still valid or should `protobuf-build` be used with recent versions of `grpcio`?

**Comment by BusyJay** [comment]
Futures 0.3 support is only merged into master and not release yet, I think the reason it works currently is grpcio uses patch to enable grpcio-compiler from master:

https://github.com/tikv/grpc-rs/blob/a1549b6ac9675d01f472956f1aed54d463903b4b/Cargo.toml#L47

Using either protoc-grpcio or protobuf-build should be OK.

Although grpcio uses protobuf-build crate for example and tests, protobuf-build is more TiKV specific, it has customization that may not be OK for everyone.

**Comment by Maher4Ever** [comment]
@BusyJay Thank you for the quick answer. I managed to get `grpcio` working with futures 0.3 by using the `master` version alone with the patched compiler.

Would it be possible to release the `master` versions of both packages to crates.io soon?

**Comment by BusyJay** [comment]
I don't have a concrete release date, but we plan to update grpc library to a latest version before bumping 0.6.0, which should be probably in early June.

`protoc-grpcio` is maintained by community, I'm not sure when will it get updated after 0.6.0 is released. I suspect it won't take long.

**Comment by Maher4Ever** [comment]
@BusyJay Great! I'll be keeping a eye on the releases page :)
