### ISSUE TITLE
Getting a SegFault with grpc-sys-0.6.0

### ISSUE THREAD

**Issue by jrconlin** [tikv/grpc-rs#478]
**Describe the bug**

My apologies if this is not directly a grpc bug. There seem to be a lot of libraries in play.

I'm getting a segfault during program startup. gdb reports:

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  __pthread_rwlock_wrlock_full (abstime=0x0, clockid=0, rwlock=0x0) at pthread_rwlock_common.c:604
604     pthread_rwlock_common.c: No such file or directory.
warning: Missing auto-load script at offset 0 in section .debug_gdb_scripts
of file /home/jrconlin/src/mozilla/syncstorage-rs/target/debug/syncstorage.
Use `info auto-load python-scripts [REGEXP]' to list them.
(gdb) bt
#0  __pthread_rwlock_wrlock_full (abstime=0x0, clockid=0, rwlock=0x0) at pthread_rwlock_common.c:604
#1  __GI___pthread_rwlock_wrlock (rwlock=0x0) at pthread_rwlock_wrlock.c:27
#2  0x000055ecafebf732 in CRYPTO_STATIC_MUTEX_lock_write (lock=0x0)
    at /home/jrconlin/.cargo/registry/src/github.com-1ecc6299db9ec823/grpcio-sys-0.6.0/grpc/third_party/boringssl-with-bazel/src/crypto/thread_pthread.c:71
#3  0x000055ecafe5a482 in CRYPTO_get_ex_new_index (ex_data_class=0x0, out_index=0x0, argl=0, argp=0x0, free_func=0x0)
    at /home/jrconlin/.cargo/registry/src/github.com-1ecc6299db9ec823/grpcio-sys-0.6.0/grpc/third_party/boringssl-with-bazel/src/crypto/ex_data.c:146
#4  0x000055ecaf61e817 in ossl_get_ssl_conn_index () at curl/lib/vtls/openssl.c:353
#5  0x000055ecaf62003b in Curl_ossl_init () at curl/lib/vtls/openssl.c:1136
#6  0x000055ecaf61c67d in Curl_ssl_init () at curl/lib/vtls/vtls.c:216
#7  0x000055ecaf5f1e54 in global_init (flags=3, memoryfuncs=bool_true) at curl/lib/easy.c:158
#8  0x000055ecaf5f1eae in curl_global_init (flags=3) at curl/lib/easy.c:217
#9  0x000055ecaf5eaa02 in curl::init::init_inner::{{closure}} () at /home/jrconlin/.cargo/registry/src/github.com-1ecc6299db9ec823/curl-0.4.31/src/lib.rs:126
#10 0x000055ecaf5df240 in std::sync::once::Once::call_once::{{closure}} () at /home/jrconlin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/sync/once.rs:264
#11 0x000055ecb0c43b7b in std::sync::once::Once::call_inner () at src/libstd/sync/once.rs:416
#12 0x000055ecaf5df1b9 in std::sync::once::Once::call_once (self=0x55ecb174f730 <curl::init::INIT>, f=...)
    at /home/jrconlin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/sync/once.rs:264
#13 0x000055ecaef8a1d1 in curl::init::init_inner () at /home/jrconlin/.cargo/registry/src/github.com-1ecc6299db9ec823/curl-0.4.31/src/lib.rs:121
#14 0x000055ecb0c766fd in __libc_csu_init ()
#15 0x00007fe0f4439040 in __libc_start_main (main=0x55ecaf0b0530 <main>, argc=1, argv=0x7fff9f2ac308, init=0x55ecb0c766b0 <__libc_csu_init>, fini=<optimized out>, rtld_fini=<optimized out>, 
    stack_end=0x7fff9f2ac2f8) at ../csu/libc-start.c:264
#16 0x000055ecaef8a20e in _start ()
```

This is with
* libssl1.1f
* libcurl4 7.68.0-1ubuntu2.1

If I use a work-around docker image that uses 
* libssl1.1d
* libcurl4 7.64.0-4+deb10u1 

I'm able to run without a problem which is not super ideal.

I'm guessing(?) this has to do with the openssl update since things seemed to work ok prior to that update being installed. I don't want to revert openssl for a lot of reasons. 

Again, my apologies if this isn't something that's directly tied to grpc, but it looks like that's the last hand off is to the vendored `boringssl-with-bazel`. Happy to refile with the appropriate package.

**To Reproduce**
Error happens on app startup.

**Expected behavior**
No seg fault.

**System information**
* CPU architecture: 
   shared: running in a VMWare VM (configured x86-64, 16GB memory, 4 hosts) on a host (6 cores, 64GB memory)
   w/ seg fault:  running native
   w/o seg fault: running in a Docker image
* Distribution and kernel version: 
   w/ seg fault: Ubuntu 20.04.1 LTS
   w/o seg fault: Debian GNU/Linux 10 (buster) (from `debian:buster-slim` with build image of `rust:1.45-buster`)
* SELinux on?: no
* Any other system details we should know?:

**Additional context**

**Comment by BusyJay** [comment]
Do you have a minimal project to reproduce the problem?

**Comment by jrconlin** [comment]
It might take me a bit to put together a toy version, but if you like, you can try running the actual server where I'm seeing the problem. https://github.com/mozilla-services/syncstorage-rs/ 

The server is dying before any config or environment is checked, so you shouldn't have to worry about setting up anything. I'd be honestly curious to see if you can reproduce the problem or if it's just something local to my instances of Ubuntu.

**Comment by BusyJay** [comment]
From the stacktrace, it seems boringssl from grpcio get mixed with openssl. I suggest to just keep using one ssl library. You can enable features "openssl" to  get rid of boringssl.

**Comment by jrconlin** [comment]
Ah! Thanks, that fixed it. Sorry about that. I guess I missed it because I didn't think it was a linker error.
