### ISSUE TITLE
The max_receive_message_len docs for setting unlimited size is incorrect

### ISSUE THREAD

**Issue by disconnect3d** [tikv/grpc-rs#491]
Tl;dr: the function  takes a `len` which is `i32`, but the documentation suggests passing `usize::MAX` which is unsigned and might not fit in `i32` value.

https://github.com/tikv/grpc-rs/blob/716f5e82b440725a1fd1d93079031c7d95e440ba/src/channel.rs#L114-L121

Please fix the either the documentation or the implementation so there is no ambiguity on how to set the received messages length limit to unlimited.

**Comment by BusyJay** [comment]
Good catch! It should be `-1`.
