### ISSUE TITLE
Why not use hyperium/tonic instead

### ISSUE THREAD

**Issue by jthinking** [tikv/grpc-rs#493]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by BusyJay** [comment]
Hyperium/tonic is an excellent project, you can choose whatever you like.

When this project was created, there was no good choices in the rust world, so we created one. This project bases on the grpc c core and keep sync with the c core about every three versions. This brings its core benefits that it can grow with the c core and get what has implemented easily. This is also a downside for a rust project that you are required to install c/c++ compiler tools.

In addition, the TiKV project has used the library in production for several years.

**Comment by BusyJay** [comment]
Close it now as the question is answered.
