### ISSUE TITLE
CMake 3.22.1 doesn't work with grpcio 

### ISSUE THREAD

**Issue by zhucan** [tikv/grpc-rs#553]
cmake version 3.22.1;
rust version 1.54.0
![image](https://user-images.githubusercontent.com/13997135/147032922-b1466ce6-e247-4651-8af9-7f2ad2088aa2.png)

**Comment by zhucan** [comment]
Upgrade gcc's version from 4.8.x to 7.3.x, it's ok

**Comment by BusyJay** [comment]
It's already in README under the Prerequisites section:

> For Linux and MacOS, you also need to install gcc 4.9+ (or clang) too.
