### ISSUE TITLE
Openssl feature pulls in boringssl

### ISSUE THREAD

**Issue by Ten0** [tikv/grpc-rs#557]
**Describe the bug**
Enabling the openssl feature pulls in 10MB of boringssl-src.
This is due to:
https://github.com/tikv/grpc-rs/blob/472ae8ac6dee4702b46d65ecac35cda0f333a64a/grpc-sys/Cargo.toml#L57-L58

**Expected behavior**
IIUC BoringSSL is not required since we're using openssl instead, so that should not be added as a dependency.

**Comment by BusyJay** [comment]
Agree. How about adding a private feature name "secure_openssl" which acts the same as `secure` except depending on `boringssl-src`.

**Comment by Ten0** [comment]
wouldn't that already be the `openssl` feature?

**Comment by BusyJay** [comment]
Using `openssl` is OK too, but when checking whether secure features are enabled, it has to be written as `cfg!(features = "openssl") || cfg!(features = "secure")`. If using a private features, then it can be defined as:
```
secure = ["boringssl-src", "_secure_enabled"]
openssl = ["_secure_enabled"]
```
So the check can be written as `cfg!(features = "_secure_enabled")`.

**Comment by Ten0** [comment]
With regards to always writing an `or` on these cfg clauses or factoring them as a private feature I have no particular opinion 🙂

Naming seems good.

**Comment by BusyJay** [comment]
Do you want to contribute this improvement?

**Comment by Ten0** [comment]
> Do you want to contribute this improvement?

I'm afraid I don't have time for this at the moment 😞
