### ISSUE TITLE
failed to build in mac

### ISSUE THREAD

**Issue by yulidai** [tikv/grpc-rs#609]
It can be compiled normally in ubuntu, but the link error always exists in mac:
```
= note: ld: warning: directory not found for option '-L/myproject/target/debug/build/libz-sys-277091bbf4c9d591/out/build'
          Undefined symbols for architecture x86_64:
            "_res_9_getservers", referenced from:
                _init_by_resolv_conf in libgrpcio_sys-3b12d8b0f67239e7.rlib(ares_init.c.o)
            "_res_9_ndestroy", referenced from:
                _init_by_resolv_conf in libgrpcio_sys-3b12d8b0f67239e7.rlib(ares_init.c.o)
            "_res_9_ninit", referenced from:
                _init_by_resolv_conf in libgrpcio_sys-3b12d8b0f67239e7.rlib(ares_init.c.o)
          ld: symbol(s) not found for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
          

error: could not compile `myproject` due to previous error
```

**Comment by yulidai** [comment]
according to the prompt, I really don't know which library is missing :(

**Comment by yulidai** [comment]
after executing `brew install libsolv`, it still hasn't been resolved

**Comment by briancorbin** [comment]
I'm also seeing this issue, on a fresh project that is only using grpcio 12. Would really appreciate some help with this.

**Comment by BusyJay** [comment]
It should be fixed on master.

**Comment by yulidai** [comment]
use `cargo run --verbose` to print compile command which like `rustc ***(a lot of params)`, copy this command and add a suffix `-lresolv` then it will compile successed.

but do not know how to specify this link info by using cargo

**Comment by yulidai** [comment]
add build.rs with content:
