### ISSUE TITLE
TiKV runs into Handshake failed with fatal error SSL_ERROR_SSL.

### ISSUE THREAD

**Issue by tonyxuqqi** [tikv/grpc-rs#619]
**Describe the bug**

The grpc-rs version is 0.10.4.

TiKV sometimes runs into this error:

2023-06-16 21:49:26 | [2023/06/16 21:49:26.773 +00:00] [ERROR] [<unknown>] ["Handshake failed with fatal error SSL_ERROR_SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number."]

The error is  from coprocessor endpoint. When it happens, it fails the coprocessor's new connection. And also it would trigger the leader election. 
It appears that some existing connections can still work as it still can have some QPS during this time. 
When this happens, there's no network package drop or 100% CPU/memory usage. The load is quite normal. 

**To Reproduce**
No exact repro step. 

**Expected behavior**

**System information**
* CPU architecture:
* Distribution and kernel version: 
* SELinux on?:
* Any other system details we should know?:

**Additional context**

**Comment by BusyJay** [comment]
Endpoint failure should not trigger elections, it may due to other reasons. The error itself is probably caused by mixing http and https requests.

**Comment by tonyxuqqi** [comment]
> Endpoint failure should not trigger elections, it may due to other reasons. The error itself is probably caused by mixing http and https requests.

Endpoint failure makes heartbeat request/response cannot be sent and thus triggers the election timeout.
