### ISSUE TITLE
Examples not compiling

### ISSUE THREAD

**Issue by christian-oudard** [tikv/grpc-rs#628]
**Describe the bug**
The examples hit a compiler error related to C++ version.

**To Reproduce**
1. `cd tests-and-examples`
2. `cargo run --example=greeter_server`
2500 lines of C++ errors:
https://gist.github.com/christian-oudard/d039e9b3248413221e192fda7bb5ab4e

**Expected behavior**
The hello server was supposed to run.

**System information**
* CPU architecture: x86_64
* Distribution and kernel version: Arch Linux, kernel 6.4.7
* SELinux on?: no
* Any other system details we should know?: -

**Additional context**

**Comment by BusyJay** [comment]
Does the issue exist with the latest master?

**Comment by christian-oudard** [comment]
Yes, the fix worked, thanks!
